### ISSUE TITLE
Should work on Windows/MSVC

### ISSUE THREAD

**Issue by thoughtpolice** [thoughtpolice/minibsdiff#1]
A windows port shouldn't be very difficult using MinGW, but MSVC will require a little caressing (some C99 uses in `test.c`, no `stdint.h`, etc.)

**Comment by lifeisdream** [comment]
In MSVC 2015, I've got

1>minibsdiff.obj : error LNK2005: _bsdiff already defined in bsdiff.obj
1>minibsdiff.obj : error LNK2005: _bsdiff_patchsize_max already defined in bsdiff.obj
1>minibsdiff.obj : error LNK2005: _bspatch already defined in bspatch.obj
1>minibsdiff.obj : error LNK2005: _bspatch_newsize already defined in bspatch.obj
1>minibsdiff.obj : error LNK2005: _bspatch_valid_header already defined in bspatch.obj
1>C:\Users\Suvorov\Desktop\diff\minibsdiff-master\minibsdiff\Release\minibsdiff.exe : fatal error LNK1169: one or more multiply defined symbols found

when compiling last version.

**Comment by lifeisdream** [comment]
and results for my given .exe file are different. 
i created patch, zlib it, and apply. and then use fc to compare files. 
Using this port they differ, using default bsdiff - they are the same (
